### PR TITLE
A few minor changes 

### PR DESCRIPTION
**Pull request by wkargul**
If you want me to implement other functionalities in your code please contact me via e-mail (wojciech.kargul@gmail.com) or write comments here. I will gladly contribute to the Open Source project written in Rust.

### CODE REVIEW

**Comment by wkargul** [comment]
Hi @pmalek-sumo,

So, by default, all logging is disabled except for the error level. Surely, we can set the default level of logging (in the case when there is no environmental variable present) in our code.

TO BE DELETED:
from receiver-mock/main.rs
`env_logger::init();`

TO BE INSERTED:
`use env_logger::Env;`

`env_logger::Builder::from_env(Env::default().default_filter_or("warn")).init();`
                                                                                                      ^
                                                                                                       |
                                                                                                       |
                                                     set desired "default" log level, to be used if env var is not present

I can implement it in the code. What do you think about it?
What's more, if you would like to have better human-readable log you might want to use [pretty_env_logger](https://crates.io/crates/pretty_env_logger )

**Comment by wkargul** [comment]
Hi Team,

Do you have any updates on that?

Regards,
Wojtek

**Comment by pmalek-sumo** [comment]
> Hi @pmalek-sumo,
> 
> So, by default, all logging is disabled except for the error level. Surely, we can set the default level of logging (in the case when there is no environmental variable present) in our code.
> 
> TO BE DELETED: from receiver-mock/main.rs `env_logger::init();`
> 
> TO BE INSERTED: `use env_logger::Env;`
> 
> `env_logger::Builder::from_env(Env::default().default_filter_or("warn")).init();`
> 
> set desired "default" log level, to be used if env var is not present (as "warn" in the example above)
> 
> I can implement it in the code. What do you think about it? What's more, if you would like to have a better human-readable log you might want to use [pretty_env_logger](https://crates.io/crates/pretty_env_logger)

Setting this by default to info sounds good to me! We'd like to retain as much as possible from the already existing behavior.

**Comment by wkargul** [comment]
If you need further help with your Rust codebase please contact me. As I see no significant interest (no review since a few months) in this PR I am closing it.

**Comment by pmalek-sumo** [comment]
> If you need further help with your Rust codebase please contact me. As I see no significant interest (no review since a few months) in this PR I am closing it.

Sorry for not getting back to you sooner on this. 😓 

We'd very much welcome PR and some of the ideas proposed in this one seem to be nice additions to receiver-mock.

If you'd still be interested in contributing I'd suggest to submit smaller PRs contributing 1 particular improvement that we can then review and merge. How does that sound?

**Pull request closed without merging**
