### PR TITLE
Run shellcheck and tests only for PRs

### PR DESCRIPTION
**Pull request by pmalek-sumo**
This also removes `branches` section as it's marked as deprecated as per https://config.travis-ci.com/ref/job/branches

> Branches
> Include or exclude branches from being built
> 
> Include or exclude branches for your build to be run on.
> 
> This is a **legacy** setting, use the more powerful condition (if) to define branches for your build to be run on.
> 
>

### CODE REVIEW

**Review by sumo-drosiek — APPROVED** [review]
Makes sense. Thanks!

**Comment by sumo-drosiek** [comment]
@pmalek-sumo Please rebase and merge 🎉

**Comment by perk-sumo** [comment]
I'm not sure I like the idea of tests being run on PRs only.
I think they should be run on the resulting commit on main branch as well, just in case something change in the meantime between branch split and merge.

**Comment by pmalek-sumo** [comment]
Since we only have rebase and squash + rebase enabled it's equivalent of running ci on "resulting commit" 
aka fast forward merge, it's just the branch tip that changes, not the commit itself

image

**Pull request merged**
