### PR TITLE
[receiver-mock] Add --print-headers flag

### PR DESCRIPTION
**Pull request by pmalek-sumo**
This PR adds `--print-headers` to print incoming request's headers in the following format:

```
--> POST / HTTP/1.1
--> host: localhost:3000
--> user-agent: Telegraf/unknown Go/1.15
--> content-length: 212
--> content-encoding: gzip
--> content-type: application/vnd.sumologic.carbon2
--> accept-encoding: gzip

```

### CODE REVIEW

**Review by sumo-drosiek — CHANGES_REQUESTED** [review]
I think the `print_headers` should be moved into `Statistics` to keep consistency and avoid passing and chaining too much parameters to the functions.
BTW, the `Statistics` should be splitted on `Statistics` and `Parameters`, but it can be done outside of this PR

**Comment by pmalek-sumo** [comment]
> I think the `print_headers` should be moved into `Statistics` to keep consistency and avoid passing and chaining too much parameters to the functions.
> BTW, the `Statistics` should be splitted on `Statistics` and `Parameters`, but it can be done outside of this PR

Hmmm but printing request's info+headers doesn't have anything to do with statistics.

If we'd like to make this fancy as it evolves I guess we could make a variadic parameter (is that a thing in Rust?) with configuration options or with a list of functions to apply on the request in `handle`. Or if that grows even further maybe just make it a proper struct with implemented methods for each route? (long reaching future if that even happens I guess)

**Comment by sumo-drosiek** [comment]
> Hmmm but printing request's info+headers doesn't have anything to do with statistics.

Thats why

```
BTW, the Statistics should be splitted on Statistics and Parameters, but it can be done outside of this PR
```

> If we'd like to make this fancy as it evolves I guess we could make a variadic parameter (is that a thing in Rust?) with configuration options or with a list of functions to apply on the request in `handle`. Or if that grows even further maybe just make it a proper struct with implemented methods for each route? (long reaching future if that even happens I guess)

I know that this solution is not as good as it could be. The idea of `Statistics` was to avoid changing the function signature with every new parameter or statistic.
Variadic parameter are possible, but IMHO it's not a pretty solutions in rust. I need to take some time and re-think the architecture.

**Comment by sumo-drosiek** [comment]
#42

**Review by sumo-drosiek — APPROVED** [review]
LGTM, going to conflict with my PR but will fix it

**Pull request merged**
