### PR TITLE
feat(receiver-mock): add caching regexes

### PR DESCRIPTION
**Pull request by aboguszewski-sumo**
Follow-up to #381 
The regexes are now being cached. 

Sadly, benchmarks in Rust are unstable, but I can try making some if needed.

### CODE REVIEW

**Review by swiatekm-sumo — APPROVED** [review]
The changes look fine, though I wouldn't mind a unit test for the regex cache. I'm not really convinced this is a net gain though. These regex sound like they'd be very simple on average, and should be fast to parse. Have you profiled how much time this actually saves?

**Comment by aboguszewski-sumo** [comment]
I have not, but in the former version, we were calculating a new regex every time we were comparing the target metadata with the actual ones in **every** log. 
I will try to do some benchmarks tomorrow.

**Comment by aboguszewski-sumo** [comment]
@swiatekm-sumo I added a test and a simple benchmark - and I think that the difference is significant. Sample results:
```
Time with cache on: 102 ms
```
```
Time with cache off: 11730 ms
```
The benchmark I did can be found at the end of `test` module in `logs/mod.rs`. It simply runs the query `n` times on `m` logs, each having `k` different metadata. The query was a simple query that checks exact matches. The results above are for `n=3, m=1000, k=20`. 
Let me know if you think that other benchmarks need to be done, but I think that this is enough to say that caching is necessary.

Inb4: I tried using benchmark libraries, but it would be troublesome to use them correctly, and the difference here is big enough that I think it's not needed.

**Comment by swiatekm-sumo** [comment]
Good enough for me, thanks for doing this :+1: . I think we're good to merge after rebasing.

**Pull request merged**
